# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-09 19:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('iidestado', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id Estado')),
                ('cdescripcion', models.CharField(blank=True, db_column='Descripcion', max_length=50, null=True, verbose_name='Estado')),
            ],
            options={
                'verbose_name_plural': 'Estados',
                'db_table': 'estado',
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iidmunicipio', models.IntegerField(db_column='Id Municipio', null=True, verbose_name='Id Municipio')),
                ('cdescripcion', models.CharField(blank=True, db_column='Descripcion', max_length=50, null=True, verbose_name='Municipio')),
                ('iidestado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.Estado')),
            ],
            options={
                'verbose_name_plural': 'Municipios',
                'db_table': 'municipio',
            },
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('iidubicacion', models.AutoField(primary_key=True, serialize=False, verbose_name='Id Ubicación')),
                ('iasentamiento', models.IntegerField(blank=True, null=True, verbose_name='Asentamiento')),
                ('cdescripcion', models.CharField(blank=True, db_column='Descripcion', max_length=80, null=True, verbose_name='Descripción')),
                ('icodigopostal', models.IntegerField(blank=True, db_column='Codigo Postal', null=True, verbose_name='Codigo Postal')),
                ('iidestado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.Estado')),
                ('iidmunicipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.Municipio')),
            ],
            options={
                'verbose_name_plural': 'Ubicaciones',
                'db_table': 'ubicacion',
            },
        ),
    ]
